import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import StreamClientProvider from "@/providers/StreamClientProvider";
import { Toaster } from "@/components/ui/toaster";

import "@stream-io/video-react-sdk/dist/css/styles.css";
import "react-datepicker/dist/react-datepicker.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <StreamClientProvider>
            {/* <Navbar /> */}

            {/* <SignedOut> */}
            {/* <SignInButton /> */}
            {/* </SignedOut> */}
            {/* <SignedIn> */}
            {/* <UserButton /> */}
            {/* </SignedIn> */}

            {children}
            <Toaster />
          </StreamClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
